version: '3'
services:
  mongodb:
    image: mongo
    restart: unless-stopped
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
  api:
    depends_on:
      - mongodb
    restart: unless-stopped
    build: .
    ports:
      - 3000:3000
    volumes:
      - ./:/app
    environment:
      - JWT_SECRET=yourJwtSec&ret#@!
      - DB_URL=mongodb://mongodb:27017/hybrid?retryWrites=true&w=majority
volumes:
  mongodb: