const express = require('express')
const bodyParser = require('body-parser')
const mongoose = require('mongoose')
const buyer = require('./routes/buyers')
const auth = require('./routes/auth')
const seller = require('./routes/seller')
const app = express()
require('dotenv').config()
app.use(bodyParser.json())
mongoose.connect(process.env.DB_URL)
app.use('/api/auth', auth)
app.use('/api/seller', seller)
app.use('/api/buyer', buyer)

app.listen(3000, console.log('listening on port 3000'))